//! Wraith Deep Browser Hardening Engine
//! Injects anti-fingerprinting and WebRTC/WebGL kill switches into Firefox profile user.js files.

use std::fs;
use std::path::{Path, PathBuf};
use tracing::info;
use walkdir::WalkDir;
use wraith_core::error::Result;

pub const FIREFOX_HARDENING_HEADER: &str = "\
// Wraith Browser Anonymization & Anti-Fingerprint Profile
// Auto-generated by Wraith // Pure Anonymity
";

pub const FIREFOX_PREFERENCES: &[(&str, &str)] = &[
    // WebRTC Leak Prevention
    ("media.peerconnection.enabled", "false"),
    ("media.peerconnection.ice.default_address_only", "true"),
    ("media.peerconnection.ice.no_host", "true"),
    ("media.peerconnection.ice.proxy_only_if_behind_proxy", "true"),

    // Hardware & Fingerprint Defenses
    ("webgl.disabled", "true"),
    ("geo.enabled", "false"),
    ("geo.wifi.uri", "\"\""),
    ("dom.battery.enabled", "false"),
    ("media.navigator.enabled", "false"),
    ("privacy.resistFingerprinting", "true"),
    ("privacy.trackingprotection.enabled", "true"),
    ("privacy.firstparty.isolate", "true"),

    // Telemetry Kill
    ("toolkit.telemetry.enabled", "false"),
    ("datareporting.healthreport.uploadEnabled", "false"),
    ("datareporting.policy.dataSubmissionEnabled", "false"),

    // DNS & Prefetch
    ("network.prefetch-next", "false"),
    ("network.dns.disablePrefetch", "true"),
    ("network.dns.disablePrefetchFromHTTPS", "true"),
    ("network.http.speculative-parallel-limit", "0"),

    // Proxy Enforce (SOCKS5 Remote DNS)
    ("network.proxy.type", "1"),
    ("network.proxy.socks", "\"127.0.0.1\""),
    ("network.proxy.socks_port", "9050"),
    ("network.proxy.socks_remote_dns", "true"),
    ("network.proxy.no_proxies_on", "\"\""),
];

pub fn find_firefox_profiles() -> Vec<PathBuf> {
    let mut profiles = Vec::new();
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".into());
    let search_roots = [
        format!("{home}/.mozilla/firefox"),
        "/root/.mozilla/firefox".to_string(),
    ];

    for root_str in &search_roots {
        let root = Path::new(root_str);
        if root.exists() && root.is_dir() {
            for entry in WalkDir::new(root).max_depth(2).into_iter().flatten() {
                let path = entry.path();
                if path.is_dir() && (path.join("prefs.js").exists() || path.to_string_lossy().contains(".default")) {
                    profiles.push(path.to_path_buf());
                }
            }
        }
    }

    profiles.sort();
    profiles.dedup();
    profiles
}

pub fn apply_firefox_hardening() -> Result<usize> {
    let profiles = find_firefox_profiles();
    let mut modified = 0;

    let mut config_lines = vec![FIREFOX_HARDENING_HEADER.to_string()];
    for (key, val) in FIREFOX_PREFERENCES {
        config_lines.push(format!("user_pref(\"{key}\", {val});"));
    }
    let full_config = config_lines.join("\n") + "\n";

    for profile in profiles {
        let user_js = profile.join("user.js");
        if fs::write(&user_js, &full_config).is_ok() {
            info!("Hardened Firefox Profile: {}", profile.display());
            modified += 1;
        }
    }

    Ok(modified)
}

pub fn remove_firefox_hardening() -> Result<usize> {
    let profiles = find_firefox_profiles();
    let mut removed = 0;

    for profile in profiles {
        let user_js = profile.join("user.js");
        if user_js.exists() {
            if let Ok(content) = fs::read_to_string(&user_js) {
                if content.contains("Wraith Browser Anonymization") {
                    let _ = fs::remove_file(&user_js);
                    removed += 1;
                }
            }
        }
    }

    info!("Removed browser hardening from {removed} profiles");
    Ok(removed)
}
