//! Wraith Deep Browser Hardening Engine
//! Injects anti-fingerprinting and WebRTC/WebGL kill switches into Firefox profile user.js files.

use std::fs;
use std::path::PathBuf;
use tracing::info;
use wraith_core::error::Result;

pub const FIREFOX_HARDENING_HEADER: &str = "\
// Wraith Browser Anonymization & Anti-Fingerprint Profile
// Auto-generated by Wraith // Pure Anonymity
";

pub const FIREFOX_PREFERENCES: &[(&str, &str)] = &[
    // WebRTC Leak Prevention
    ("media.peerconnection.enabled", "false"),
    ("media.peerconnection.ice.default_address_only", "true"),
    ("media.peerconnection.ice.no_host", "true"),
    ("media.peerconnection.ice.proxy_only_if_behind_proxy", "true"),

    // Hardware & Fingerprint Defenses
    ("webgl.disabled", "true"),
    ("geo.enabled", "false"),
    ("geo.wifi.uri", "\"\""),
    ("dom.battery.enabled", "false"),
    ("media.navigator.enabled", "false"),
    ("privacy.resistFingerprinting", "true"),
    ("privacy.trackingprotection.enabled", "true"),
    ("privacy.firstparty.isolate", "true"),

    // Telemetry Kill
    ("toolkit.telemetry.enabled", "false"),
    ("datareporting.healthreport.uploadEnabled", "false"),
    ("datareporting.policy.dataSubmissionEnabled", "false"),

    // DNS & Prefetch
    ("network.prefetch-next", "false"),
    ("network.dns.disablePrefetch", "true"),
    ("network.dns.disablePrefetchFromHTTPS", "true"),
    ("network.http.speculative-parallel-limit", "0"),

    // Proxy Enforce (SOCKS5 Remote DNS)
    ("network.proxy.type", "1"),
    ("network.proxy.socks", "\"127.0.0.1\""),
    ("network.proxy.socks_port", "9050"),
    ("network.proxy.socks_remote_dns", "true"),
    ("network.proxy.no_proxies_on", "\"\""),
];

pub fn find_firefox_profiles() -> Vec<PathBuf> {
    crate::anti_fingerprint::find_all_firefox_profiles().unwrap_or_default()
}

pub fn apply_firefox_hardening() -> Result<usize> {
    let profiles = find_firefox_profiles();
    let mut modified = 0;

    let mut config_lines = vec![FIREFOX_HARDENING_HEADER.to_string()];
    for (key, val) in FIREFOX_PREFERENCES {
        config_lines.push(format!("user_pref(\"{key}\", {val});"));
    }
    let full_config = config_lines.join("\n") + "\n";

    for profile in profiles {
        let user_js = profile.join("user.js");
        if write_managed_preferences(&user_js, Some(&full_config)).is_ok() {
            info!("Hardened Firefox Profile: {}", profile.display());
            modified += 1;
        }
    }

    Ok(modified)
}

pub fn remove_firefox_hardening() -> Result<usize> {
    let profiles = find_firefox_profiles();
    let mut removed = 0;

    for profile in profiles {
        let user_js = profile.join("user.js");
        write_managed_preferences(&user_js, None)?;
        removed += 1;
    }

    info!("Removed browser hardening from {removed} profiles");
    Ok(removed)
}

const MANAGED_BEGIN: &str = "// WRAITH MANAGED PREFERENCES BEGIN";
const MANAGED_END: &str = "// WRAITH MANAGED PREFERENCES END";

pub(crate) fn write_managed_preferences(path: &std::path::Path, payload: Option<&str>) -> Result<()> {
    use std::io::Write;
    use wraith_core::error::WraithError;
    #[cfg(target_os = "linux")]
    let (_parent_handle, pinned_path) = pin_preference_parent(path)?;
    #[cfg(target_os = "linux")]
    let path = pinned_path.as_path();
    if let Ok(metadata) = fs::symlink_metadata(path) {
        if !metadata.is_file() || metadata.file_type().is_symlink() {
            return Err(WraithError::Forensic("Refusing non-regular browser preference file".into()));
        }
    }
    let read_original = || -> std::io::Result<String> {
        use std::io::Read;
        let mut options = fs::OpenOptions::new();
        options.read(true);
        #[cfg(target_os = "linux")] {
            use std::os::unix::fs::OpenOptionsExt;
            options.custom_flags(libc::O_NOFOLLOW | libc::O_NONBLOCK);
        }
        let mut file = options.open(path)?;
        if !file.metadata()?.is_file() { return Err(std::io::Error::other("Preferences must be a regular file")); }
        let mut content = String::new();
        file.read_to_string(&mut content)?;
        Ok(content)
    };
    let original = match read_original() {
        Ok(text) => text,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => return Err(e.into()),
    };
    let mut retained = original.clone();
    if let Some(start) = retained.find(MANAGED_BEGIN) {
        let end = retained[start..].find(MANAGED_END)
            .ok_or_else(|| WraithError::Forensic("Incomplete managed preference block".into()))?
            + start + MANAGED_END.len();
        retained.replace_range(start..end, "");
    } else if payload.is_none() {
        return Ok(());
    }
    if let Some(payload) = payload {
        retained.push_str(&format!("\n{MANAGED_BEGIN}\n{payload}\n{MANAGED_END}\n"));
    }
    let parent = path.parent().ok_or_else(|| WraithError::Forensic("Missing profile directory".into()))?;
    let mut temp = tempfile::NamedTempFile::new_in(parent)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::MetadataExt;
        use std::os::fd::AsRawFd;
        let owner = fs::metadata(parent)?;
        // The browser user must retain access when Wraith runs as root.
        let result = unsafe { libc::fchown(temp.as_raw_fd(), owner.uid(), owner.gid()) };
        if result != 0 { return Err(std::io::Error::last_os_error().into()); }
    }
    temp.write_all(retained.as_bytes())?;
    temp.as_file().sync_all()?;
    temp.persist(path).map_err(|e| e.error)?;
    Ok(())
}

#[cfg(target_os = "linux")]
fn pin_preference_parent(path: &std::path::Path) -> Result<(fs::File, std::path::PathBuf)> {
    use std::os::{fd::AsRawFd, unix::fs::OpenOptionsExt};
    use std::path::{Component, Path, PathBuf};
    use wraith_core::error::WraithError;
    let absolute = if path.is_absolute() { path.to_path_buf() } else { std::env::current_dir()?.join(path) };
    let parent = absolute.parent().ok_or_else(|| WraithError::Forensic("Missing profile parent".into()))?;
    let mut directory = fs::File::open("/")?;
    for component in parent.components() {
        match component {
            Component::RootDir | Component::CurDir => {},
            Component::Normal(name) => {
                let anchored = PathBuf::from(format!("/proc/self/fd/{}", directory.as_raw_fd())).join(name);
                directory = fs::OpenOptions::new().read(true)
                    .custom_flags(libc::O_DIRECTORY | libc::O_NOFOLLOW).open(anchored)?;
            }
            _ => return Err(WraithError::Forensic("Invalid profile parent path".into())),
        }
    }
    let anchored = Path::new(&format!("/proc/self/fd/{}", directory.as_raw_fd())).join(absolute.file_name().unwrap());
    Ok((directory, anchored))
}

#[cfg(test)]
mod preference_tests {
    use super::*;
    #[cfg(target_os = "linux")]
    #[test]
    fn refuses_symlinked_profile_parent() {
        let dir = tempfile::tempdir().unwrap();
        let real = dir.path().join("real");
        fs::create_dir(&real).unwrap();
        let linked = dir.path().join("linked");
        std::os::unix::fs::symlink(&real, &linked).unwrap();
        assert!(write_managed_preferences(&linked.join("user.js"), Some("test")).is_err());
        assert!(!real.join("user.js").exists());
    }

    #[test]
    fn preserves_user_preferences_across_apply_and_remove() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("user.js");
        fs::write(&path, "user_pref(\"custom.setting\", true);\n").unwrap();
        write_managed_preferences(&path, Some("user_pref(\"privacy.setting\", true);")).unwrap();
        write_managed_preferences(&path, Some("user_pref(\"privacy.setting\", false);")).unwrap();
        let content = fs::read_to_string(&path).unwrap();
        assert_eq!(content.matches(MANAGED_BEGIN).count(), 1);
        write_managed_preferences(&path, None).unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap().trim(), "user_pref(\"custom.setting\", true);");
    }
}
