[package]
name = "wraith-net"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wraith-core = { version = "1.4.3", path = "../wraith-core" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
rand.workspace = true
nix.workspace = true
tempfile.workspace = true
libc.workspace = true
tokio.workspace = true
tokio-util.workspace = true
zeroize.workspace = true
rust-i18n = "4.2.1"

[target.'cfg(target_os = "linux")'.dev-dependencies]
socket2 = { version = "0.6", features = ["all"] }
etherparse = "0.20"
